### ISSUE TITLE
Can't run single method test

### ISSUE THREAD

**Issue by 4lex1v** [rranelli/maven-test-mode#2]
Hi! This plugin is actually what i was looking for. I have one legacy Scala project that's still using Maven and it seems like your package should solve all my problems, but unfortunately it doesn't run single method tests, when i enter "C-c , s" it returns "No test definition before point". The project uses TestNG as a testing engine. Can you help to fix this? I would really like to use your plugin

**Comment by rranelli** [comment]
Hi 4lex1v, thanks for the interest!

Are you trying to run the tests when viewing the class file or the test file? Currently, you can only run the single-method test when viewing a test file.

Can you run the full test suite ? (with C-c , a or `maven-test-all`)

The test function uses the variable `maven-test-test-method-name-re` [here](https://github.com/rranelli/maven-test-mode/blob/master/maven-test-mode.el#L71):

The default value will match test methods with the following pattern:

``` java
public void test_method_name_here {
// ... test code
}
```

The plugin will generate a command `mvn test -Dtest=testClassName#test_method_name_here`

If your tests do not match this, you need to change the regexp in `maven-test-test-method-name-re` The test method name must be in the first matching group.

**Comment by 4lex1v** [comment]
Yes, e.g file is called UserRestTest.scala, but it looks like the problem is that your `maven-test-test-method-name-re` is bound to Java syntax, e.g `public void test_method_name_here`, but it's different in Scala, like this:

`def shouldReportAlreadyExistsErrorWhenCreatingUserInAnotherAgency(): Unit = ???`

I'm not sure if it's possible to do so, but is it possible to rebind the matching from the method to the annotation, i.e `@Test`? As i understand this annotation is using in all Java projects and this will suite me too.

**Comment by rranelli** [comment]
The main problem actually is formatting the test command. I by no means claim to understand anything about maven.

Can you confirm if the command `mvn test -Dtest=TestFileName#testMethod` works?
If the command works I just need to adapt the regexp to accept both syntax.

**Comment by 4lex1v** [comment]
Yes, of course. I can run test from CLI and IDEA. And i can also run all your other commands, except `maven-test-method`

**Comment by rranelli** [comment]
Right! I'm actually understand very little of the Java ecosystem.

I will adapt the regexp and everything will work (I hope).

**Comment by rranelli** [comment]
As a workaround, you can add `(setq maven-test-test-method-name-re "def \\([a-zA-Z]+\\).*\s*=\s*\n?")` and it will probably work.

I'm working now on a better way to do this.

**Comment by rranelli** [comment]
Can you check if [this version](https://github.com/rranelli/maven-test-mode/blob/add-support-for-scala-tests/maven-test-mode.el) fixes your issue??

It's a bad implementation, but if it works I'll refactor.

Thanks!

**Comment by 4lex1v** [comment]
Ok, checked and it works, thanks!

**Comment by rranelli** [comment]
Thank you for the effort ;)
